-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 16:28:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rentastudent
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rentastudent` ;

-- -----------------------------------------------------
-- Schema rentastudent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rentastudent` DEFAULT CHARACTER SET utf8 ;
USE `rentastudent` ;

-- -----------------------------------------------------
-- Table `rentastudent`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`login` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`login` (
  `iduser` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `createDate` DATETIME NOT NULL,
  `updateDate` DATETIME NOT NULL,
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentastudent`.`bedrijf_gegevens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`bedrijf_gegevens` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`bedrijf_gegevens` (
  `iduser` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  `plaats` VARCHAR(45) NULL,
  `Bedrijf` VARCHAR(45) NULL,
  `postcode` VARCHAR(12) NULL,
  `createDate` DATETIME NOT NULL,
  `updateDate` DATETIME NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `iduser_idx` (`iduser` ASC),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `idlogin`
    FOREIGN KEY (`iduser`)
    REFERENCES `rentastudent`.`login` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentastudent`.`opdrachten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`opdrachten` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`opdrachten` (
  `idopdracht` INT NOT NULL,
  `iduser` INT NOT NULL,
  `titel` VARCHAR(45) NOT NULL,
  `loon` VARCHAR(45) NOT NULL,
  `tot_uur` VARCHAR(45) NOT NULL,
  `datum` VARCHAR(45) NOT NULL,
  `beschrijving` TEXT NOT NULL,
  `createDate` DATETIME NOT NULL,
  `updateDate` DATETIME NOT NULL,
  PRIMARY KEY (`idopdracht`, `iduser`),
  INDEX `iduser_idx` (`iduser` ASC),
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `rentastudent`.`bedrijf_gegevens` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentastudent`.`factuur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`factuur` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`factuur` (
  `idfactuur` INT NOT NULL,
  `idopdracht` INT NOT NULL,
  `prijs_ex` INT NOT NULL,
  `prijs_inc` INT NOT NULL,
  `btw` INT NULL,
  `tot_uur` INT NOT NULL,
  `loon` DECIMAL NOT NULL,
  `datum` DATETIME NOT NULL,
  `factuurdatum` DATETIME NOT NULL,
  `vervaldatum` DATETIME NOT NULL,
  `bank` VARCHAR(100) NOT NULL,
  `iban` VARCHAR(100) NOT NULL,
  `bic` VARCHAR(100) NOT NULL,
  `btwnr` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfactuur`),
  INDEX `idopdracht_idx` (`idopdracht` ASC),
  CONSTRAINT `idopdracht`
    FOREIGN KEY (`idopdracht`)
    REFERENCES `rentastudent`.`opdrachten` (`idopdracht`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentastudent`.`rollen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`rollen` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`rollen` (
  `idrollen` INT NOT NULL,
  `titel` VARCHAR(45) NOT NULL,
  `createDate` DATETIME NOT NULL,
  `updateDate` DATETIME NOT NULL,
  PRIMARY KEY (`idrollen`),
  UNIQUE INDEX `idrollen_UNIQUE` (`idrollen` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentastudent`.`student_gegvens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`student_gegvens` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`student_gegvens` (
  `iduser` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `woonplaats` VARCHAR(45) NULL,
  `straat` VARCHAR(45) NULL,
  `huisnummer` INT NULL,
  `cv` BLOB NULL,
  `postcode` VARCHAR(12) NULL,
  `createDate` DATETIME NOT NULL,
  `updateDate` DATETIME NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `iduser_idx` (`iduser` ASC)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentastudent`.`opdrachten_reacties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`opdrachten_reacties` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`opdrachten_reacties` (
  `idopdracht` INT NOT NULL,
  `iduser` INT NOT NULL,
  `createDate` DATETIME NOT NULL,
  `updateDate` DATETIME NOT NULL,
  PRIMARY KEY (`idopdracht`, `iduser`),
  INDEX `idopdracht_idx` (`idopdracht` ASC),
  INDEX `iduser_idx` (`iduser` ASC)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentastudent`.`rollen_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rentastudent`.`rollen_link` ;

CREATE TABLE IF NOT EXISTS `rentastudent`.`rollen_link` (
  `iduser` INT NOT NULL,
  `idrollen` INT NOT NULL,
  `createDate` DATETIME NOT NULL,
  `updateDate` DATETIME NOT NULL,
  INDEX `idrollen_idx` (`idrollen` ASC),
  PRIMARY KEY (`iduser`, `idrollen`))
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
